### ISSUE TITLE
Increase bcrypt cost

### ISSUE THREAD

**Issue by 0xdabbad00** [apexskier/httpauth#18]
You use a bcrypt cost of 8 (https://github.com/apexskier/httpauth/blob/master/auth.go#L177).  Go's default bcrypt cost is 10 (https://github.com/golang/crypto/blob/master/bcrypt/bcrypt.go#L23).  Not really an important issue.  You may want to make this configurable.

**Comment by apexskier** [comment]
Thanks for the update. I'm still going to hard code for now, because I don't know how I'd implement the configuration off the top of my head. Pull requests are welcome, of course.

**Comment by 0xdabbad00** [comment]
May be relevant to point out that this is a breaking change with previous code, because if someone upgraded your library to this update, they would need to re-generate hashes.

**Comment by apexskier** [comment]
Thanks!

**Comment by 0xdabbad00** [comment]
Looks like a couple more spots need to be updated. 

- https://github.com/apexskier/httpauth/blob/f1b3ec531b1cd5d3e0e5371f1c6de9a23025dd07/examples/server.go#L41
- https://github.com/apexskier/httpauth/blob/f1b3ec531b1cd5d3e0e5371f1c6de9a23025dd07/auth.go#L219
