### ISSUE TITLE
Password salting with username is useless

### ISSUE THREAD

**Issue by superduper** [apexskier/httpauth#5]
I think its redundant. Here's a [piece of code](https://code.google.com/p/go/source/browse/bcrypt/bcrypt.go?repo=crypto#143) that does salting when `bcrypt.GenerateFromPassword` used.

**Comment by 0xdabbad00** [comment]
I noticed this as well.  It does look odd, but it doesn't hurt anything, and could be viewed as maybe "good" in case the system ran out of good random (for example, if on program start-up it added a million new users, the system would likely start generating random that isn't really that random).  However, for this use of random, that's not really that much of a problem.

One problem with this, is that you can't change a user's name without also having them re-enter or change their password.  In most use cases, you would likely be asking a user to re-enter their username credentials anyway to change their username, but this is unexpected for developers.
